### ISSUE TITLE
"ext:bookmark_pages" for "ext:news"

### ISSUE THREAD

**Issue by typo3ua** [colorcube/bookmark_pages#1]
For the "ext:news" can to configure the "text: bookmark pages"?

**Comment by colorcube** [comment]
If the question is if bookmark_pages work with news, the answer is yes. bookmark_pages only bookmark urls. As long as each news has it's own url it will work.

**Comment by typo3ua** [comment]
The standard configuration for any url...? Does the URL news need a special configuration?

**Comment by colorcube** [comment]
Just try it out if it works for your setup. bookmark_pages is not that hard to install.

**Comment by typo3ua** [comment]
I did all that written in manual and I see all that in part 2 of manual.

But I added a bookmark button on detail page where I did Include the plugin ext:news and this function on this page not work.

Here [Login page](http://dev.typo3.org.ua/) / ... - is working

Here [Topic...](http://dev.typo3.org.ua/) - is not working

**Comment by colorcube** [comment]
Sorry, that's not enough information to help you.

**Comment by typo3ua** [comment]
I use:
Last TYPO3 and extension
Here Login:
```
User: admin
Password: password
```
What you need so as that will help me?
