### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by konradmichalik** [colorcube/bookmark_pages#2]
Please add PHP 7.2 compatibility to the bookmark_pages extension.

**Comment by colorcube** [comment]
What problems do you have?

There's a php dependency in ext_emconf.php, which I will remove. Anything else?

**Comment by colorcube** [comment]
Sorry I looked in an old version. There's no php dependency in ext_emconf.php.

Still the question is what errors do you have?

**Comment by colorcube** [comment]
I tested with php 7.0 and 7.2 without any problems.

**Comment by konradmichalik** [comment]
I'm sorry, the issue seems to be in a dependency. The [typoscript_rendering](https://github.com/helhum/typoscript_rendering) extension has a php constraint in their ext_emconf.php. So I got the error message while I was trying to install your extension via composer. 

https://github.com/helhum/typoscript_rendering/issues/45

**Comment by konradmichalik** [comment]
As mentioned in the issue from the extension typoscript_rendering, can you require helhum/typoscript-rendering instead of the ter version?

**Comment by colorcube** [comment]
done
Thank you for finding this
